config/routes.rb
NotificationCentre::Application.routes.draw do
  resources :applications do
    resources :received_updates
  end

  match '/:app_name/webhook' => "applications#webhook" 

  match '/:app_name/received_updates' => "received_updates#index"

   root :to => 'applications#index'

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :name, :url

  validates_presence_of :name, :url

  has_many :received_updates, :dependent => :destroy
end

app/models/received_update.rb
class ReceivedUpdate < ActiveRecord::Base
  attr_accessible :agency_id, :name, :obj_id, :time

  belongs_to :application

  validates_presence_of :agency_id, :name, :obj_id
  
  def self.since(since = 1.month.ago )
    since ||= 1.month.ago 
    where("time >= ?", since )    
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  # 
  # 
  
  skip_before_filter  :verify_authenticity_token, only: [:webhook]
  
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  def webhook
    @application = Application.find_by_name params.delete(:app_name)
    params.delete(:controller)
    params.delete(:action)
    params[:obj_id] = params[:object_id]
    params.delete(:object_id)
    x = @application.received_updates.create(params)
    puts x.inspect
    puts "valid? : #{x.valid?}"
    render :nothing => true
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id]) rescue nil
    @applicaiton = Application.find_by_name(params[:id]) if @application.blank?

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    @application = Application.new(params[:application])

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/received_updates_controller.rb
class ReceivedUpdatesController < ApplicationController
  # GET /received_updates
  # GET /received_updates.json

  def index
    @application = Application.find(params[:application_id]) rescue nil
    name = params[:app_name] || params[:application_id]
    @application = Application.find_by_name(name) if @application.blank?
    since = Time.parse(params[:since]).utc rescue nil
    agency_id = params[:agency_id] || ( params[:search][:agency_id] unless params[:search].blank? )

    condition = agency_id.blank? ? "1=1" : "agency_id='#{agency_id}'"
    
    unless params[:search].blank? 
      condition += " and name='#{params[:search][:type]}'" unless params[:search][:type].blank? || params[:search][:type] == "Any"
      condition += " and obj_id='#{params[:search][:object_id]}'" unless params[:search][:object_id].blank? 
    end
    
    @received_updates = @application.received_updates.where(condition).since( since ).order("created_at desc")
    
    @update_types = ["agency.update", "agent.create", "agent.update", "attendances.create", "attendances.delete",
       "contact.create", "contact.delete", "contact.update", "floorplans.update", "inspections.create", "inspections.update",
        "listing.create", "listing.update", "photos.update", "questions.update", "subscriptions.update", "virtual_realities.update"].collect{ |x| [x,x] }
        
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @received_updates }
    end
  end

  # GET /received_updates/1
  # GET /received_updates/1.json
  def show
    @received_update = ReceivedUpdate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @received_update }
    end
  end

  # GET /received_updates/new
  # GET /received_updates/new.json
  def new
    @application = Application.find(params[:application_id])
    @received_update = @application.received_updates.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @received_update }
    end
  end

  # GET /received_updates/1/edit
  def edit
    @received_update = ReceivedUpdate.find(params[:id])
  end

  # POST /received_updates
  # POST /received_updates.json
  def create
    #@received_update = ReceivedUpdate.new(params[:received_update])
    @application = Application.find(params[:application_id])
    @received_update = @application.received_updates.new(params[:received_update])

    respond_to do |format|
      if @received_update.save
        format.html { redirect_to application_received_updates_path(@received_update.application), notice: 'Received update was successfully created.' }
        format.json { render json: @received_update, status: :created, location: @received_update }
      else
        format.html { render action: "new" }
        format.json { render json: @received_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /received_updates/1
  # PUT /received_updates/1.json
  def update
    @received_update = ReceivedUpdate.find(params[:id])

    respond_to do |format|
      if @received_update.update_attributes(params[:received_update])
        format.html { redirect_to @received_update, notice: 'Received update was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @received_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /received_updates/1
  # DELETE /received_updates/1.json
  def destroy
    @received_update = ReceivedUpdate.find(params[:id])
    @received_update.destroy

    respond_to do |format|
      format.html { redirect_to received_updates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/received_updates_helper.rb
module ReceivedUpdatesHelper
end

app/views/applications/_form.html.erb
<%= simple_form_for @application, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :url %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                applications_path, :class => 'btn' %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<%- model_class = @application.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applications/index.html.erb
<%- model_class = Application.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= link_to application.name, application_path(application) %></td>
        <td><%= application.url %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_application_path(application), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      application_path(application),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_application_path,
            :class => 'btn btn-primary' %>

app/views/applications/new.html.erb
<%- model_class = @application.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/applications/show.html.erb
<%- model_class = @application.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
  <br></br>
  <p><%= link_to "Received Updates", application_received_updates_path(@application) %></p>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @application.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @application.url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              applications_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_application_path(@application), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              application_path(@application),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NotificationCentre</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="#">iDashboard Notification Centre</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Applications", applications_path %></li>
            <li><%= link_to "Contact Us" %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
<div class="container">
  <div class="span12">
  <%= yield %>
</div>
</div>

</body>
</html>

app/views/received_updates/_form.html.erb
<%= simple_form_for @received_update, :url => application_received_updates_path(params[:application_id]), :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :agency_id %>
  <%= f.input :obj_id %>
  <%= f.input :time , :as => :datetime %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                application_received_updates_path(params[:application_id]), :class => 'btn' %>
  </div>
<% end %>

app/views/received_updates/edit.html.erb
<%- model_class = @received_update.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/received_updates/index.html.erb
<%- model_class = ReceivedUpdate.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= simple_form_for :search, :url => application_received_updates_path(params[:application_id]),:method => 'GET', :html => { :class => 'form-inline' } do |f| %>
<table class="table table-striped">
  <tbody>
		<tr>
			<td><%= f.select :type, @update_types, :required => false, :include_blank => "Any" %></td>
  		<td><%= f.input :agency_id, :label => false,  :placeholder => "Agency id" , :required => false %></td>
    	<td><%= f.input :object_id , :label => false, :placeholder => "Object id", :required => false%></td>
			<td> <%= pluralize( @received_updates.count, "Update") %> </td>
    	<td><%= f.button :submit, "Filter", :class => 'btn-primary' %></td>
		</tr>
  </tbody>
</table>
<% end %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:agency_id) %></th>
      <th><%= model_class.human_attribute_name(:obj_id) %></th>
      <th><%= model_class.human_attribute_name(:time) %></th>
      <!--th><%=t '.actions', :default => t("helpers.actions") %></th-->
    </tr>
  </thead>
  <tbody>
    <% @received_updates.each do |received_update| %>
      <tr>
        <td><%= link_to received_update.name, application_received_update_path(received_update.application, received_update) %></td>
        <td><%= received_update.agency_id %></td>
        <td><%= received_update.obj_id %></td>
        <td><%= received_update.time %></td>
        <!--td>
          <% link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_application_received_update_path(received_update.application, received_update), :class => 'btn btn-mini' %>
          <% link_to t('.destroy', :default => t("helpers.links.destroy")),
                      application_received_update_path( received_update.application, received_update),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td-->
      </tr>
    <% end %>
  </tbody>
</table>

<% link_to t('.new', :default => t("helpers.links.new")),
            new_application_received_update_path(@application),
            :class => 'btn btn-primary' %>

app/views/received_updates/new.html.erb
<%- model_class = @received_update.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/received_updates/show.html.erb
<%- model_class = @received_update.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @received_update.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:agency_id) %>:</strong></dt>
  <dd><%= @received_update.agency_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:obj_id) %>:</strong></dt>
  <dd><%= @received_update.obj_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:time) %>:</strong></dt>
  <dd><%= @received_update.time %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              received_updates_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_received_update_path(@received_update), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              received_update_path(@received_update),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>